### ISSUE TITLE
What is the reason to do that?

### ISSUE THREAD

**Issue by pronvis** [imager-io/ffmpeg-dev-rs#10]
What is the reason to do that?
https://github.com/imager-io/ffmpeg-dev-rs/blob/b8dc9f73bfe6b8b5389ab4f744c1da6f05cdfb49/examples/remux.rs#L183

**Comment by colbyn** [comment]
Regarding

https://github.com/imager-io/ffmpeg-dev-rs/blob/b8dc9f73bfe6b8b5389ab4f744c1da6f05cdfb49/examples/remux.rs#L183

Honestly I don’t remember why. It’s possible I was being paranoid and wanted to ensure that any associated drop implementations got called (unsafe rust is confusing sometimes, let alone the insanity of FFmpeg C APIs, though perhaps it's just me LOL).
